from typing import Protocol

from .projectorPower import _powerState


class ProjectorTransportDriver(Protocol):
    """Minimum interface for a projector driver to support."""
    def poweron(self) -> None: ...
    def poweroff(self) -> None: ...
    def cool(self) -> None: ...
    def get_raw_power_state(self) -> _powerState: ...
